// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview AI-powered transaction categorization flow.
 *
 * - categorizeTransaction - Categorizes a transaction based on description.
 * - CategorizeTransactionInput - The input type for categorizeTransaction.
 * - CategorizeTransactionOutput - The return type for categorizeTransaction.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CategorizeTransactionInputSchema = z.object({
  transactionDescription: z
    .string()
    .describe('The description of the transaction to categorize.'),
});
export type CategorizeTransactionInput = z.infer<typeof CategorizeTransactionInputSchema>;

const CategorizeTransactionOutputSchema = z.object({
  category: z.string().describe('The predicted category for the transaction.'),
  confidence: z
    .number()
    .describe('The confidence level for the categorization (0-1).'),
});
export type CategorizeTransactionOutput = z.infer<typeof CategorizeTransactionOutputSchema>;

export async function categorizeTransaction(
  input: CategorizeTransactionInput
): Promise<CategorizeTransactionOutput> {
  return categorizeTransactionFlow(input);
}

const categorizeTransactionPrompt = ai.definePrompt({
  name: 'categorizeTransactionPrompt',
  input: {schema: CategorizeTransactionInputSchema},
  output: {schema: CategorizeTransactionOutputSchema},
  prompt: `You are an expert financial advisor that helps categorize transactions into categories.

  Given the following transaction description, determine the most appropriate category and a confidence level between 0 and 1.

  Transaction Description: {{{transactionDescription}}}
  `,
});

const categorizeTransactionFlow = ai.defineFlow(
  {
    name: 'categorizeTransactionFlow',
    inputSchema: CategorizeTransactionInputSchema,
    outputSchema: CategorizeTransactionOutputSchema,
  },
  async input => {
    const {output} = await categorizeTransactionPrompt(input);
    return output!;
  }
);
